# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1594914f601fec5421388ccab3140e498e329b8ffbce77ff9fa72f8f867e56299c9c435f03746f989ca559b1029d2cb627458dc52c505942575068633c6813eb

test:
  secret_key_base: 4803990fd9f2ba2cc55664d84c5625d65b0e0e1747a9bd28ab5216a5df1259273d36db7a9976b35af54ab1a4dee49386d4cc695b72e3612d07ebb370a3058684

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
